#!/bin/sh
set -e

# Reload udev & systemd
if [ -d /run/systemd/system ]; then
    systemctl daemon-reload || true
    systemctl enable --now battery-charge-threshold.service || true
    udevadm control --reload-rules || true
    udevadm trigger --subsystem-match=power_supply || true
    systemctl kill --kill-who=main --signal=HUP systemd-logind.service || true
fi

# Update desktop & icon caches
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database -q /usr/share/applications || true
fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
fi

exit 0
